### ISSUE TITLE
AttributeError: 'Dataset' object has no attribute 'datadir'

### ISSUE THREAD

**Issue by LMJOK** [JaySaligia/PPT#15]
出现了以下的问题。Traceback (most recent call last):
  File "D:\Git_CoderLife\git_download\PPT-master\PPT-master\software\PPT.py", line 365, in <module>
    id_entity, entity_id = D.get_entity_by_id()
  File "D:\Git_CoderLife\git_download\PPT-master\PPT-master\software\dataset.py", line 32, in get_entity_by_id
    return get_id_dict(self.datadir + '/{}/entity2id.txt'.format(self.dataset))
AttributeError: 'Dataset' object has no attribute 'datadir'

**Comment by xuetianqi** [comment]
请问您解决这个问题了吗

**Comment by cmjcoding** [comment]
我也是！！！蹲一个解决办法，929126004@qq.com
